### ISSUE TITLE
Following sequence of commands is broken

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub-cli#11]
```
$ pfhub download meumapps_bm1a
$ pfhub convert ./meta.yaml
$ pfhub upload meta.yaml --sandbox
Traceback (most recent call last):
  File "/nix/store/f8z5pv614wsxqcsgsbmhmiizf821fjaw-python3.10-poetry2nix-env-scripts/bin/.pfhub-wrapped", line 13, in <module>
    sys.exit(cli())
... 
  File "/nix/store/sfyy2wshqjwflxg35i86c2lrxv7yjcdv-python3-3.10.13-env/lib/python3.10/site-packages/toolz/itertoolz.py", line 454, in get
    return seq[ind]
KeyError: 'summary'
```

**Comment by wd15** [comment]
Stupid, should be uploading `pfhub.yaml`. Resolved.
